"""Add Veiculo model.

Revision ID: 3b1e69ac9e21
Revises: 
Create Date: 2025-01-26 20:23:58.808722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b1e69ac9e21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_constraint('empresa_celular_key', type_='unique')
        batch_op.drop_constraint('empresa_email_key', type_='unique')

    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.alter_column('cnh_categ',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.alter_column('cnh_categ',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.create_unique_constraint('empresa_email_key', ['email'])
        batch_op.create_unique_constraint('empresa_celular_key', ['telefone'])
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
