"""Add tabela Veiculo.

Revision ID: 76f23e70bce1
Revises: 3b1e69ac9e21
Create Date: 2025-01-26 20:31:55.147631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f23e70bce1'
down_revision = '3b1e69ac9e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('MOTOCICLETA', 'CARRO', 'UTILITARIO', 'CAMINHAO', 'OUTROS', name='tipos'), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('renavam', sa.String(length=50), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('chassis', sa.String(length=50), nullable=False),
    sa.Column('proprio', sa.Integer(), nullable=True),
    sa.Column('licenciamento', sa.Date(), nullable=True),
    sa.Column('ipva', sa.Date(), nullable=True),
    sa.Column('observacao_Carro', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chassis'),
    sa.UniqueConstraint('placa'),
    sa.UniqueConstraint('renavam')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('veiculo')
    # ### end Alembic commands ###
